[package]
name = "rpc-sync-client"
version = "0.9.0-alpha"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Utilities for connection to the 0MQ RPC server via blocking synchronous calls"

[dependencies]
# Internal Dependencies
rpc-common = { path = "../rpc-common" }

# Serialization & Data Formats
bincode.workspace = true

# Networking & Communication
zmq.workspace = true

# Error Handling & Logging
tracing.workspace = true

# Utilities & Helpers
uuid.workspace = true
