[package]
name = "moor-web-host"
version = "0.9.0-alpha"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "A RESTful web front end for interacting with the mooR system"

[package.metadata.deb]
depends = "$auto, systemd, openssl"
extended-description = "Process for listening for HTTP requests and forwarding them to a mooR daemon."
section = "net"
license-file = ["../../LICENSE", "0"]
priority = "optional"
assets = [
    ["target/release/moor-web-host", "/usr/bin/moor-web-host", "755"],
    [
        "debian/moor-web-host.service",
        "/lib/systemd/system/moor-web-host.service",
        "644",
    ],
    ["debian/web-host.yaml", "/etc/moor/web-host.yaml", "644"],
    ["src/client/*", "/var/lib/moor-web-host/", "644"],
]
maintainer-scripts = "debian/scripts"
systemd-units = { enable = false }

[dependencies]
# Internal Dependencies
moor-common = { path = "../common" }
moor-var = { path = "../var" }
rpc-async-client = { path = "../rpc/rpc-async-client" }
rpc-common = { path = "../rpc/rpc-common" }

# Command Line & Configuration
clap.workspace = true
clap_derive.workspace = true
figment.workspace = true

# Serialization & Data Formats
base64.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true

# Networking & Communication
axum.workspace = true
tmq.workspace = true
tower-http.workspace = true

# Async Runtime & Concurrency
futures-util.workspace = true
tokio.workspace = true

# Error Handling & Logging
color-eyre.workspace = true
eyre.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

# Utilities & Helpers
uuid.workspace = true

#
rolldown = { git = "https://github.com/rolldown/rolldown" }

[build-dependencies]
rolldown = { git = "https://github.com/rolldown/rolldown" }
tokio = { workspace = true, features = ["rt", "macros", "sync", "rt-multi-thread"] }
