[package]
name = "moor-var"
version = "0.9.0-alpha"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "The set of primitive MOO value types across the system"

# dev dependencies only for linux...
[target.'cfg(all(target_os = "linux"))'.dev-dependencies]
perf-event2.workspace = true

[dev-dependencies]
minstant.workspace = true
serde_json.workspace = true
shuttle.workspace = true

[target.'cfg(all(target_os = "linux"))']
[[bench]]
name = "var_benches"
harness = false

[dependencies]
ahash.workspace = true
binary-layout.workspace = true
bincode.workspace = true
boxcar.workspace = true
byteview.workspace = true
im.workspace = true
lazy_static.workspace = true
num-traits.workspace = true
once_cell.workspace = true
papaya.workspace = true
paste.workspace = true
serde.workspace = true
strum.workspace = true
thiserror.workspace = true
unicase.workspace = true
