[package]
name = "moor-common"
version = "0.9.0-alpha"
authors.workspace = true
build = "build.rs"
categories.workspace = true
edition.workspace = true
keywords.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "The set of values, and model/entities used across the system"

[build-dependencies]
shadow-rs.workspace = true

[dependencies]
moor-var = { path = "../var" }

binary-layout.workspace = true
bincode.workspace = true
byteview.workspace = true
crossbeam-utils.workspace = true
enum-primitive-derive.workspace = true
fast-counter.workspace = true
itertools.workspace = true
lazy_static.workspace = true
minstant.workspace = true
num-traits.workspace = true
serde.workspace = true
shadow-rs.workspace = true
strum.workspace = true
thiserror.workspace = true
uuid.workspace = true

[features]
default = []
perf_counters = []
